/**
 * Environment Configuration Script
 *
 * This script generates environment.ts files from environment variables.
 * Run before building: node scripts/set-env.js
 *
 * For local development: Create .env file from .env.example
 * For CI/CD: Set environment variables in your platform (Vercel, GitHub Actions, etc.)
 */

const fs = require('fs');
const path = require('path');

// Try to load .env file if it exists (for local development)
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  require('dotenv').config({ path: envPath });
  console.log('✅ Loaded environment from .env file');
} else {
  console.log('ℹ️  No .env file found, using system environment variables');
}

// Required environment variables
const requiredVars = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];

// Check for missing variables
const missing = requiredVars.filter(v => !process.env[v]);
if (missing.length > 0) {
  console.error('❌ Missing required environment variables:');
  missing.forEach(v => console.error(`   - ${v}`));
  console.error('\nFor local development:');
  console.error('  1. Copy .env.example to .env');
  console.error('  2. Fill in the values');
  console.error('\nFor CI/CD:');
  console.error('  Set these variables in your deployment platform');
  process.exit(1);
}

// Environment configuration
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;
const redirectUrl = process.env.REDIRECT_URL || 'http://localhost:4200/auth/callback';

// Determine if production based on NODE_ENV
const isProduction = process.env.NODE_ENV === 'production';

// Generate environment.ts content
const environmentContent = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/set-env.js
// To modify, update .env file and run: node scripts/set-env.js

export const environment = {
  production: ${isProduction},
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
  redirectUrl: '${redirectUrl}',
};
`;

// Write environment files
const environmentsDir = path.join(__dirname, '..', 'src', 'environments');

// Ensure directory exists
if (!fs.existsSync(environmentsDir)) {
  fs.mkdirSync(environmentsDir, { recursive: true });
}

// Write main environment.ts
fs.writeFileSync(
  path.join(environmentsDir, 'environment.ts'),
  environmentContent
);
console.log('✅ Generated src/environments/environment.ts');

console.log('\n🎉 Environment configuration complete!');
